SELECT I.TABLE_NAME, I.INDEX_NAME, C.COLUMN_NAME, I.UNIQUENESS, C.DESCEND,
       (CASE WHEN EXISTS (SELECT * FROM USER_CONSTRAINTS WHERE INDEX_NAME=I.INDEX_NAME AND CONSTRAINT_TYPE='P') THEN 1 ELSE 0 END) IS_PK
FROM USER_INDEXES I
         INNER JOIN USER_IND_COLUMNS C ON I.INDEX_NAME = C.INDEX_NAME %s
ORDER BY I.TABLE_NAME, I.INDEX_NAME, C.COLUMN_POSITION;